---

# 获取snapshotclone的版本
- name: get snapshotclone version
  vars:
    metric_port: "{{ snapshot_dummy_port }}"
    curve_version:
  include_tasks: common_tasks/get_curve_version_from_metric.yml

- name: set need restart false
  set_fact:
    need_restart: false
  when: curve_version == expected_curve_version

- name: restart snapshot-clone
  vars:
    ch_dir: "{{ deploy_dir }}"
    daemon_script: ./snapshot-daemon.sh
    ping_port: "{{ snapshot_dummy_port }}"
    check_health: true
  include_tasks: restart_by_daemon.yml
  when: need_restart
