---

# 获取mds的版本
- name: get curve version
  vars:
    metric_port: "{{ mds_dummy_port }}"
    curve_version:
  include_tasks: common_tasks/get_curve_version_from_metric.yml

- name: set need_restart false
  set_fact:
    need_restart: false
  when: curve_version == expected_curve_version

- name: restart mds
  include_tasks: restart_by_daemon.yml
  vars:
    ch_dir: "{{ deploy_dir }}"
    daemon_script: ./mds-daemon.sh
    ping_port: "{{ mds_dummy_port }}"
    check_health: true
  when: need_restart
