---

- name: update config
  ignore_errors: true
  shell: sudo puppet agent -t
  register: result

- name: fail when return code is not 2
  fail:
    msg: "puppet agent -t return code is {{ result.rc }}"
  when: result.rc != 2

