---
# Copyright 2020 NetEase, Inc.
# The config check of curve

- name: check chunkserver config
  hosts: chunkservers
  become: yes
  become_user: "{{ sudo_user }}"
  become_flags: -iu {{ sudo_user }}

  tasks:
    - include_tasks: "common_tasks/check_chunkserver.yml"
